"use client";

import { useState } from "react";
import type { KundliResponse } from "@/lib/types";
import { buildChalitChart } from "@/lib/jyotish-ui";
import NorthChart from "./NorthChart";
import SouthChart from "./SouthChart";

type Style = "north" | "south";

export default function BhavaChalit({ data }: { data: KundliResponse }) {
  const [style, setStyle] = useState<Style>("north");
  const chalit = data.kundli.chalit;
  const cd = buildChalitChart(data);

  if (!chalit || !cd) {
    return (
      <p className="meta-line">
        The Bhava Chalit chart isn’t available for this chart (it was generated by an
        earlier version). Regenerate the chart to compute it.
      </p>
    );
  }

  const shifted = chalit.planets.filter((p) => p.shifted);
  const bb = data.kundli.bhavatBhavam;

  return (
    <div className="chalit-wrap">
      <p className="sl-intro">
        The Bhava Chalit places each planet in the house it truly falls in, using bhavas
        centred on the ascendant degree. Planets near a sign edge can sit in a different
        house here than in the Rashi (D1) chart — those are flagged below.
      </p>

      <div className="varga-toolbar">
        <div className="seg">
          <button className={`seg-btn${style === "north" ? " active" : ""}`} onClick={() => setStyle("north")}>
            North Indian
          </button>
          <button className={`seg-btn${style === "south" ? " active" : ""}`} onClick={() => setStyle("south")}>
            South Indian
          </button>
        </div>
      </div>

      {style === "north" ? (
        <NorthChart data={cd} title="Bhava Chalit" />
      ) : (
        <SouthChart data={cd} title="Bhava Chalit" />
      )}

      <h3 className="sl-heading">Planets that shift house in Chalit</h3>
      {shifted.length === 0 ? (
        <p className="meta-line">No planet changes house — every planet stays in its Rashi-chart house.</p>
      ) : (
        <div className="av-scroll">
          <table className="av-table sl-table">
            <thead>
              <tr><th>Planet</th><th>Rashi house (D1)</th><th>Chalit house</th></tr>
            </thead>
            <tbody>
              {shifted.map((p) => (
                <tr key={p.name}>
                  <td className="av-planet">{p.name}</td>
                  <td>House {p.rashiHouse}</td>
                  <td>House {p.bhava}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <h3 className="sl-heading">Bhavat Bhavam · House from House</h3>
      <p className="sl-intro">
        To judge any matter, also weigh the house that is as far from it as it is from the
        lagna (the “house from the house”). Below is the chart-specific reading of each
        pair — its lords, where they sit, and which grahas tenant it.
      </p>
      {bb ? (
        <div className="av-scroll">
          <table className="av-table sl-table">
            <thead>
              <tr>
                <th>House</th>
                <th>Sign · Lord</th>
                <th>Reinforced by</th>
                <th>Reading</th>
              </tr>
            </thead>
            <tbody>
              {bb.houses.map((row) => (
                <tr key={row.house}>
                  <td className="av-planet">
                    {row.house}. <span className="bb-sig">{row.significations}</span>
                  </td>
                  <td>
                    {row.signName} · {row.lord}
                    <span className="sl-abbr"> (in H{row.lordHouse})</span>
                  </td>
                  <td>
                    H{row.bbHouse} · {row.bbSignName} · {row.bbLord}
                    <span className="sl-abbr"> (in H{row.bbLordHouse})</span>
                  </td>
                  <td className="sl-note">
                    {row.planetsInHouse.length > 0 && (
                      <span className="bb-tenants">In house: {row.planetsInHouse.join(", ")}. </span>
                    )}
                    {row.note}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <p className="meta-line">Bhavat Bhavam isn’t available — regenerate the chart to compute it.</p>
      )}
    </div>
  );
}
