"use client";

import { useState } from "react";
import type { KundliResponse } from "@/lib/types";
import { formatDMS, buildLagnaChart } from "@/lib/jyotish-ui";
import NorthChart from "./NorthChart";
import SouthChart from "./SouthChart";

type Point = NonNullable<KundliResponse["kundli"]["specialLagnas"]>["lagnas"][number];
type Style = "north" | "south";

function PointTable({ points }: { points: Point[] }) {
  return (
    <div className="av-scroll">
      <table className="av-table sl-table">
        <thead>
          <tr>
            <th>Point</th>
            <th>Sign</th>
            <th>Degree</th>
            <th>Significance</th>
          </tr>
        </thead>
        <tbody>
          {points.map((p) => (
            <tr key={p.name}>
              <td className="av-planet">
                {p.name} <span className="sl-abbr">{p.abbr}</span>
              </td>
              <td>{p.rashiName}</td>
              <td>{p.longitude != null ? formatDMS(p.longitude) : "— sign only"}</td>
              <td className="sl-note">{p.note}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default function SpecialLagnas({ data }: { data: KundliResponse }) {
  const [style, setStyle] = useState<Style>("north");
  const sl = data.kundli.specialLagnas;
  if (!sl) {
    return (
      <p className="meta-line">
        Special lagnas aren’t available for this chart (it was generated by an earlier
        version). Regenerate the chart to compute them.
      </p>
    );
  }

  return (
    <div className="sl-wrap">
      <p className="sl-intro">
        Special ascendants and shadow points used in classical Vedic analysis. Each special
        lagna is cast as a full chart — its sign becomes the 1st house and the planets are
        placed around it, read just like the Rashi (D1) chart for its own significations.
      </p>

      <div className="varga-toolbar">
        <div className="seg">
          <button className={`seg-btn${style === "north" ? " active" : ""}`} onClick={() => setStyle("north")}>
            North Indian
          </button>
          <button className={`seg-btn${style === "south" ? " active" : ""}`} onClick={() => setStyle("south")}>
            South Indian
          </button>
        </div>
      </div>

      <div className="varga-grid">
        {sl.lagnas.map((p) => {
          const cd = buildLagnaChart(data, p.rashi);
          return (
            <div className="varga-cell" key={p.name}>
              {style === "north" ? (
                <NorthChart data={cd} title={`${p.name} · ${p.rashiName}`} />
              ) : (
                <SouthChart data={cd} title={`${p.name} · ${p.rashiName}`} />
              )}
              <p className="varga-purpose">{p.note}</p>
            </div>
          );
        })}
      </div>

      <h3 className="sl-heading">Special Lagnas · Positions</h3>
      <PointTable points={sl.lagnas} />

      <h3 className="sl-heading">Upagrahas · Shadow Sub-planets</h3>
      <PointTable points={sl.upagrahas} />
    </div>
  );
}
