"use client";

import { useState } from "react";
import type { KundliResponse } from "@/lib/types";
import { formatDMS, buildLagnaChart, buildLagnaHouses } from "@/lib/jyotish-ui";
import ChartWithHouses from "./ChartWithHouses";

type Point = NonNullable<KundliResponse["kundli"]["specialLagnas"]>["lagnas"][number];
type Style = "north" | "south";

function PointTable({ points }: { points: Point[] }) {
  return (
    <div className="av-scroll">
      <table className="av-table sl-table">
        <thead>
          <tr>
            <th>Point</th>
            <th>Sign</th>
            <th>Degree</th>
            <th>Significance</th>
          </tr>
        </thead>
        <tbody>
          {points.map((p) => (
            <tr key={p.name}>
              <td className="av-planet">
                {p.name} <span className="sl-abbr">{p.abbr}</span>
              </td>
              <td>{p.rashiName}</td>
              <td>{p.longitude != null ? formatDMS(p.longitude) : "— sign only"}</td>
              <td className="sl-note">{p.note}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default function SpecialLagnas({ data }: { data: KundliResponse }) {
  const [style, setStyle] = useState<Style>("north");
  const [idx, setIdx] = useState(0);
  const sl = data.kundli.specialLagnas;

  if (!sl) {
    return (
      <p className="meta-line">
        Special lagnas aren’t available for this chart (it was generated by an earlier
        version). Regenerate the chart to compute them.
      </p>
    );
  }

  const lagnas = sl.lagnas;
  const cur = lagnas[Math.max(0, Math.min(idx, lagnas.length - 1))];
  const cd = buildLagnaChart(data, cur.rashi);
  const houses = buildLagnaHouses(data, cur.rashi);
  const step = (d: number) => setIdx((idx + d + lagnas.length) % lagnas.length);

  return (
    <div className="sl-wrap">
      <p className="sl-intro">
        Each special ascendant is cast as a full chart — its sign becomes the 1st house and
        the planets are placed around it. Pick a lagna below, then tap any house to read its
        sign, lord and planets.
      </p>

      <div className="varga-toolbar">
        <div className="seg">
          <button className={`seg-btn${style === "north" ? " active" : ""}`} onClick={() => setStyle("north")}>
            North Indian
          </button>
          <button className={`seg-btn${style === "south" ? " active" : ""}`} onClick={() => setStyle("south")}>
            South Indian
          </button>
        </div>

        <div className="varga-picker">
          <button className="btn-ghost varga-nav" onClick={() => step(-1)} aria-label="Previous lagna">‹</button>
          <select value={idx} onChange={(e) => setIdx(Number(e.target.value))}>
            {lagnas.map((p, i) => (
              <option key={p.name} value={i}>
                {p.name} — {p.rashiName}
              </option>
            ))}
          </select>
          <button className="btn-ghost varga-nav" onClick={() => step(1)} aria-label="Next lagna">›</button>
        </div>
      </div>

      <ChartWithHouses
        key={cur.name + style}
        chartData={cd}
        title={`${cur.name} · ${cur.rashiName}`}
        houses={houses}
        style={style}
      />
      <p className="varga-count">
        {cur.note} · Lagna {idx + 1} of {lagnas.length}
      </p>

      <h3 className="sl-heading">Special Lagnas · Positions</h3>
      <PointTable points={lagnas} />

      <h3 className="sl-heading">Upagrahas · Shadow Sub-planets</h3>
      <PointTable points={sl.upagrahas} />
    </div>
  );
}
