import type { KundliResponse } from "@/lib/types";
import { formatDMS } from "@/lib/jyotish-ui";

type Point = NonNullable<KundliResponse["kundli"]["specialLagnas"]>["lagnas"][number];

function PointTable({ points }: { points: Point[] }) {
  return (
    <div className="av-scroll">
      <table className="av-table sl-table">
        <thead>
          <tr>
            <th>Point</th>
            <th>Sign</th>
            <th>Degree</th>
            <th>Significance</th>
          </tr>
        </thead>
        <tbody>
          {points.map((p) => (
            <tr key={p.name}>
              <td className="av-planet">
                {p.name} <span className="sl-abbr">{p.abbr}</span>
              </td>
              <td>{p.rashiName}</td>
              <td>{p.longitude != null ? formatDMS(p.longitude) : "— sign only"}</td>
              <td className="sl-note">{p.note}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default function SpecialLagnas({ data }: { data: KundliResponse }) {
  const sl = data.kundli.specialLagnas;
  if (!sl) {
    return (
      <p className="meta-line">
        Special lagnas aren’t available for this chart (it was generated by an earlier
        version). Regenerate the chart to compute them.
      </p>
    );
  }

  return (
    <div className="sl-wrap">
      <p className="sl-intro">
        Special ascendants and shadow points used in classical Vedic analysis. Each is
        read like a lagna for its own significations. Indu and Varnada are sign-only
        points by tradition; the rest carry an exact degree.
      </p>

      <h3 className="sl-heading">Special Lagnas</h3>
      <PointTable points={sl.lagnas} />

      <h3 className="sl-heading">Upagrahas · Shadow Sub-planets</h3>
      <PointTable points={sl.upagrahas} />
    </div>
  );
}
